runtime: python39
entrypoint: gunicorn -b :$5432 app:app

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/p4ds-team-3:asia-northeast3:postgresql-machine/.s.PGSQL.5432
  DB_USER: postgres
  DB_PASS: kants123!
  DB_NAME: kants

beta_settings:
  cloud_sql_instances: p4ds-team-3:asia-northeast3:postgresql-machine
  